//
// Created by Olcay Taner YILDIZ on 21.07.2022.
//

#ifndef INFORMATIONRETRIEVAL_TERMWEIGHTING_H
#define INFORMATIONRETRIEVAL_TERMWEIGHTING_H

enum class TermWeighting{
    NATURAL = 0,
    LOGARITHM,
    BOOLE
};
#endif //INFORMATIONRETRIEVAL_TERMWEIGHTING_H
