//
// Created by Olcay Taner YILDIZ on 3.12.2022.
//

#ifndef INFORMATIONRETRIEVAL_CATEGORYDETERMINATIONTYPE_H
#define INFORMATIONRETRIEVAL_CATEGORYDETERMINATIONTYPE_H

enum class CategoryDeterminationType{
    KEYWORD = 0,
    COSINE
};

#endif //INFORMATIONRETRIEVAL_CATEGORYDETERMINATIONTYPE_H
