//
// Created by Olcay Taner YILDIZ on 21.07.2022.
//

#ifndef INFORMATIONRETRIEVAL_RETRIEVALTYPE_H
#define INFORMATIONRETRIEVAL_RETRIEVALTYPE_H

enum class RetrievalType{
    BOOLEAN = 0,
    POSITIONAL,
    RANKED,
    ATTRIBUTE
};
#endif //INFORMATIONRETRIEVAL_RETRIEVALTYPE_H
