//
// Created by Olcay Taner YILDIZ on 19.10.2022.
//

#ifndef INFORMATIONRETRIEVAL_DOCUMENTTYPE_H
#define INFORMATIONRETRIEVAL_DOCUMENTTYPE_H

enum class DocumentType{
    NORMAL = 0,
    CATEGORICAL
};

#endif //INFORMATIONRETRIEVAL_DOCUMENTTYPE_H
