//
// Created by Olcay Taner YILDIZ on 21.07.2022.
//

#ifndef INFORMATIONRETRIEVAL_DOCUMENTWEIGHTING_H
#define INFORMATIONRETRIEVAL_DOCUMENTWEIGHTING_H

enum class DocumentWeighting{
    NO_IDF = 0,
    IDF,
    PROBABILISTIC_IDF
};
#endif //INFORMATIONRETRIEVAL_DOCUMENTWEIGHTING_H
