//
// Created by Olcay Taner YILDIZ on 21.07.2022.
//

#ifndef INFORMATIONRETRIEVAL_INDEXTYPE_H
#define INFORMATIONRETRIEVAL_INDEXTYPE_H

enum class IndexType{
    INCIDENCE_MATRIX = 0,
    INVERTED_INDEX
};
#endif //INFORMATIONRETRIEVAL_INDEXTYPE_H
